development:
  sessions:
    default:
      database: monster_catcher_development
      hosts:
      - localhost:27017

test:
  sessions:
    default:
      database: monster_catcher_test
      hosts:
      - localhost:27017
